/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef, useState } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

const revSpeed = (2 * Math.PI) / 3;
let lastElapsed = 0;
let animationTime = 0;

const Model = (props) => {
  let delta;
  let elapsed;
  const group = useRef();
  const [animating, setAnimating] = useState(true);
  const { nodes, materials } = useGLTF("./DRT-Text.gltf");

  useFrame((state) => {
    elapsed = state.clock.getElapsedTime();
    delta = elapsed - lastElapsed;
    lastElapsed = elapsed;

    if (animating) {
      group.current.position.y += 10 * delta;
      if (group.current.position.y < 0) {
        group.current.position.y = 0;
        group.current.rotation.y = 0;
      }
      // DEBUG
      //console.log(`time = ${animationTime}`);
      animationTime += delta;
      if (animationTime < 0) {
        animationTime = 0;
        group.current.position.y = 0;
        group.current.rotation.y = 0;
      }
      // DEBUG
      //console.log(`animation time = ${animationTime}`);
      group.current.rotation.y += revSpeed * delta;
      setAnimating(animationTime < 3);
    }
  });

  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        {...props}
        geometry={nodes.DRT001.geometry}
        material={materials.Orange}
        position={[-10, -17, 0]}
        scale={[10, 10, 10]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/DRT-Text.gltf");

export default Model;
