/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

const Model = (props) => {
  const group = useRef();
  const { nodes, materials } = useGLTF("/DRT-Text.gltf");
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.DRT001.geometry}
        material={materials.Orange}
        position={[-1.09, -0.44, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
};

useGLTF.preload("/DRT-Text.gltf");

export default Model;
